<option value="Account">Account</option>
<option value="Admission">Admission</option>
<option value="Bio-Chemistry & Bio-Technology ">Bio-Chemistry & Bio-Technology </option>
<option value="Biomedical">Biomedical</option>
<option value="Business Administration">Business Administration</option>
<option value="Canteen">Canteen</option>
<option value="Computer Science & Engineering">Computer Science & Engineering</option>
<option value="Electric & Electronics Engineering">Electric & Electronics Engineering</option>
<option value="Information Technology">Information Technology</option>
<option value="Islamic Studies">Islamic Studies</option>
<option value="Law">Law</option>
<option value="Library">Library</option>
<option value="Library Information System">Library Information System</option>
<option value="Management Information System">Management Information System</option>
<option value="Mechatronic Engineering">Mechatronic Engineering</option>
<option value="Pharmacy">Pharmacy</option>
<option value="Pharmacy">Registrar</option>
<option value="Store ">Store </option>
<option value="Textile & Engineering">Textile & Engineering </option>
<option value="Treasurer ">Treasurer </option>
<option value="Vice Chancellor ">Vice Chancellor </option>

